services:
  mysql:
    container_name: 'mysqlChat'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabaseChat'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3000:3306'